{% set name = "kedro-pack" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  noarch: python
  number: 0

requirements:
  host:
    - python >=3.10,<3.11
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.10,<3.11
    - kedro >=0.18.12,<0.19.0
    - kedro-datasets >=1.6.0,<2.0.0
    - kedro-airflow >=0.6.0,<1.0.0
    - kedro-mlflow >=0.11.9,<1.0.0
    - kedro-viz >=6.4.0,<7.0.0
    - kedro-light >=2023.3.13

test:
  imports:
    - kedro
    - kedro_datasets
    - kedro_airflow
    - kedro_mlflow
    - kedro_viz
  requires:
    - pip

about:
  home: https://github.com/ResponsibleAIML/kedro-pack
  summary: Installation of the kedro framework and desired plugins
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - millsks
